import { useRef, useState } from 'react';
import ReactMarkdown from 'react-markdown';

const DISCLAIMER_TEXT = `
### Terms and Conditions of Use AskMeInsurance

**1. Nature of Service**

This chatbot is a demonstration project created for **educational and professional portfolio purposes**. It is **not** a licensed financial institution, insurance provider, or advisor. The information provided by this chatbot is for general informational purposes only and does not constitute financial, insurance, legal, or professional advice.

**2. No Reliance**

The content generated by this tool is produced by an artificial intelligence model. AI systems are prone to "hallucinations," errors, and inaccuracies. You should not rely on any information provided by this chatbot to make insurance, investment, or personal financial decisions. Always consult with a certified financial consultant or a qualified insurance professional before acting on any information.

**3. Data Privacy and Collection**

By using this service, you acknowledge that:

* Your interaction with the chatbot, including any text input, may be processed to generate responses.
* If you provide an email address, it is collected solely for demonstration purposes (e.g., to simulate a lead-capture feature). It will not be used for marketing, sold to third parties, or used for any purpose beyond the scope of this portfolio project.
* **Important:** You must not input any sensitive personal data, such as your NRIC, financial account numbers, health records, or other private information.

**4. Limitation of Liability**

To the maximum extent permitted by Singapore law, the creator of this chatbot disclaims all liability for any direct, indirect, or consequential loss or damage arising from your use of, or reliance on, the information provided by this chatbot. The service is provided on an "as-is" and "as-available" basis.

**5. Acceptance of Terms**

By clicking "I Agree" or by continuing to use this chatbot, you signify that you have read, understood, and agreed to these terms. If you do not agree, please exit the application immediately.
`;

interface DisclaimerModalProps {
  onAgree: () => void;
  onExit: () => void;
}

export function DisclaimerModal({ onAgree, onExit }: DisclaimerModalProps) {
  const scrollRef = useRef<HTMLDivElement>(null);
  const [reachedBottom, setReachedBottom] = useState(false);

  function handleScroll() {
    const el = scrollRef.current;
    if (!el) return;
    if (el.scrollTop + el.clientHeight >= el.scrollHeight - 8) {
      setReachedBottom(true);
    }
  }

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center">
      <div className="absolute inset-0 bg-black/40" />
      <div className="relative w-full max-w-md mx-4 rounded-2xl bg-white shadow-xl p-6 flex flex-col gap-5">
        <div className="flex flex-col gap-1">
          <h2 className="text-lg font-semibold text-gray-900">Terms and Conditions</h2>
          <div className="h-px bg-gray-100 mt-1" />
        </div>

        <div
          ref={scrollRef}
          onScroll={handleScroll}
          className="overflow-y-auto max-h-80 text-sm text-gray-600 leading-relaxed [&_h3]:text-base [&_h3]:font-semibold [&_h3]:text-gray-900 [&_h3]:mt-3 [&_h3]:mb-1 [&_p]:mb-3 [&_strong]:text-gray-800 [&_ul]:pl-5 [&_ul]:mb-3 [&_li]:mb-1"
        >
          <ReactMarkdown>{DISCLAIMER_TEXT}</ReactMarkdown>
        </div>

        {!reachedBottom && (
          <p className="text-xs text-gray-400 text-center -mt-2">Scroll to the bottom to continue</p>
        )}

        <div className="flex gap-3 justify-end pt-1">
          <button
            type="button"
            onClick={onExit}
            className="px-4 py-2 rounded-lg text-sm font-medium text-gray-600 border border-gray-200 hover:bg-gray-50 transition-colors"
          >
            Exit
          </button>
          <button
            type="button"
            onClick={onAgree}
            disabled={!reachedBottom}
            className={`px-4 py-2 rounded-lg text-sm font-medium text-white transition-colors ${
              reachedBottom
                ? 'bg-neutral-900 hover:bg-neutral-700 cursor-pointer'
                : 'bg-neutral-300 cursor-not-allowed'
            }`}
          >
            Agree
          </button>
        </div>
      </div>
    </div>
  );
}
