import type { Message } from '../types';

const sampleDiagram = {
  elements: [
    {
      id: 'rect-system',
      type: 'rectangle',
      x: 80,
      y: 80,
      width: 220,
      height: 80,
      strokeColor: '#2563eb',
      backgroundColor: '#dbeafe',
      fillStyle: 'solid',
      strokeWidth: 2,
      roughness: 1,
      opacity: 100,
      seed: 1001,
      version: 1,
      versionNonce: 12001,
      isDeleted: false,
      groupIds: [],
      angle: 0,
      roundness: { type: 3 },
    },
    {
      id: 'text-system',
      type: 'text',
      x: 112,
      y: 108,
      width: 140,
      height: 24,
      strokeColor: '#1e3a8a',
      backgroundColor: 'transparent',
      fillStyle: 'solid',
      strokeWidth: 1,
      roughness: 0,
      opacity: 100,
      seed: 1002,
      version: 1,
      versionNonce: 12002,
      isDeleted: false,
      groupIds: [],
      angle: 0,
      text: 'System Prompt',
      fontSize: 20,
      fontFamily: 1,
      textAlign: 'center',
      verticalAlign: 'middle',
      baseline: 18,
      lineHeight: 1.2,
    },
    {
      id: 'rect-skill',
      type: 'rectangle',
      x: 360,
      y: 220,
      width: 220,
      height: 80,
      strokeColor: '#059669',
      backgroundColor: '#d1fae5',
      fillStyle: 'solid',
      strokeWidth: 2,
      roughness: 1,
      opacity: 100,
      seed: 1003,
      version: 1,
      versionNonce: 12003,
      isDeleted: false,
      groupIds: [],
      angle: 0,
      roundness: { type: 3 },
    },
    {
      id: 'text-skill',
      type: 'text',
      x: 426,
      y: 248,
      width: 88,
      height: 24,
      strokeColor: '#064e3b',
      backgroundColor: 'transparent',
      fillStyle: 'solid',
      strokeWidth: 1,
      roughness: 0,
      opacity: 100,
      seed: 1004,
      version: 1,
      versionNonce: 12004,
      isDeleted: false,
      groupIds: [],
      angle: 0,
      text: 'Skills',
      fontSize: 20,
      fontFamily: 1,
      textAlign: 'center',
      verticalAlign: 'middle',
      baseline: 18,
      lineHeight: 1.2,
    },
    {
      id: 'arrow-link',
      type: 'arrow',
      x: 300,
      y: 160,
      width: 72,
      height: 56,
      strokeColor: '#475569',
      backgroundColor: 'transparent',
      fillStyle: 'hachure',
      strokeWidth: 2,
      roughness: 1,
      opacity: 100,
      seed: 1005,
      version: 1,
      versionNonce: 12005,
      isDeleted: false,
      groupIds: [],
      angle: 0,
      points: [
        [0, 0],
        [72, 56],
      ],
      endArrowhead: 'arrow',
    },
  ],
};

export const textOnlyMessages: Message[] = [
  {
    id: '1',
    role: 'user',
    content: 'why is it that the premiums to be paid is generated by the financial adviser only? is there any tools/sources out there that has this information?',
  },
  {
    id: '2',
    role: 'bot',
    content: `The specific annual premium you would need to pay is typically generated by a financial adviser because insurance premiums in Singapore are highly individualised and subject to strict regulatory oversight.

While the **Product Summary** provides a general overview of the plan, here is why you won't find your specific premium amount in that document and what other tools are available:

**Why Premiums are Generated by Advisers**

- **Individual Risk Assessment:** Premiums are calculated based on your age, gender, health status (underwriting), and smoking habits. A standard document cannot account for these variables.

- **Customisable Plan Features:** The Manulife IncomeSecure plan has multiple variables that directly impact the premium, including:
  - **Premium Payment Term:** Choosing a 5-year or 10-year payment period.
  - **Sum Insured:** The "notional value" you select to determine your future income and bonuses.`,
    thinking: `The user is asking about why insurance premiums require a financial adviser to generate. Let me think through this carefully.

Insurance premiums in Singapore are regulated by MAS (Monetary Authority of Singapore). The key reasons are individual underwriting requirements and product complexity.`,
  },
];

export const canvasMessages: Message[] = [
  {
    id: '1',
    role: 'user',
    content: 'can you illustrate the difference in the canvas?',
  },
  {
    id: '2',
    role: 'bot',
    content: `I will create an interactive comparison tool in the canvas to help you visualise how these two architectural layers interact within an AI agent.

This tool will allow you to see the "Brain" of the AI toggling between the **System Prompt** (its permanent personality) and **Skills** (its specialised toolsets), with a live simulation of how the context window changes for each.`,
    hasDiagram: true,
    diagramTitle: 'System Prompt vs Skills',
    diagramData: sampleDiagram,
  },
];
